website/__init__.py
from flask import Flask

def create_app():
    app=Flask(__name__)
    app.config['SECRET_KEY']='hugougyuohuvhuovu'

    from .views import views
    app.register_blueprint(views,url_prefix='/')

    return app

website/views.py
from flask import Blueprint,render_template,request,redirect,url_for,send_file,session
import os
from pytube import YouTube
from io import BytesIO



views=Blueprint('views',__name__)


           

       
       



@views.route('/',methods=['GET','POST'])
def home():
    if request.method=='POST':
           session['url_vid']=request.form.get('url_vid')
           try:
            vid = YouTube(session['url_vid'])
            vid.check_availability()
           except:
            return "<p>ERROR</>" 
           return render_template('download.html',vid=vid)
        
    return render_template('home.html')


@views.route('/result',methods=['GET','POST'])
def result():
    if request.method=='POST':
           vid = YouTube(session['url_vid'])
           stream=vid.streams.filter(only_audio=True).first()
           buffer=BytesIO()
           stream.stream_to_buffer(buffer)
           buffer.seek(0)
           title=vid.title
           title=str(title)
           return send_file(buffer, as_attachment=True,download_name=f'{title}.mp3',mimetype='audio/mp3') 
    return render_template('download.html')

website/templates/download.html
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>youtube mp3 converter</title>
</head>
<body>
  <div class="card">
    <div class="card-header">
      Upedian tool
    </div>
    <div class="card-body">
      <h5 class="card-title">Youtube vid to mp3 and cropper</h5>
      <p class="card-text">Convert your youtube videos to mp3</p>
      <form method="post" action="{{url_for('views.result')}}"   >
        click download to convert {{vid.title}} to mp3
        <button type="submit" class="btn btn-primary">download</button>
      </form>
    </div>
  </div>
    </div>
  </div>
</body>
</html>

website/templates/home.html
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>youtube mp3 converter</title>
</head>
<body>
  <div class="card">
    <div class="card-header">
      Upedian tool
    </div>
    <div class="card-body">
      <h5 class="card-title">Youtube vid to mp3 and cropper</h5>
      <p class="card-text">Convert your youtube videos to mp3</p>
      <form method="post"  >
        <div class="form-group">
          <label for="exampleInputPassword1">url</label>
          <input type="Text" name="url_vid" class="form-control" id="exampleInputPassword1" placeholder="enter url of youtube vid ">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>     
    </div>
  </div>
</body>
</html>